services:
  # 1. FastAPI Backend Web Service
  - type: web
    name: bidnexus-ai-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: gem_bid_nexus_super_secret_key_sih26100_2026_production_key
      - key: MONGODB_URL
        value: mongodb://hemanthreddyg444_db_user:ePUAe1UsJiGPpj9f@ac-ghcjf0m-shard-00-00.t4ru2fh.mongodb.net:27017,ac-ghcjf0m-shard-00-01.t4ru2fh.mongodb.net:27017,ac-ghcjf0m-shard-00-02.t4ru2fh.mongodb.net:27017/?ssl=true&replicaSet=atlas-ma3sro-shard-0&authSource=admin&appName=Cluster0
      - key: MONGODB_DB_NAME
        value: bidnexus_ai
      - key: LLM_PROVIDER
        value: auto

  # 2. React Vite Frontend Static Site
  - type: web
    name: bidnexus-ai-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
